# Generated by Django 5.0.7 on 2024-08-13 23:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_learning_entry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Learning_Entry',
            new_name='LearningEntry',
        ),
    ]
