# Generated by Django 5.0.7 on 2024-08-14 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0005_rename_learning_entry_learningentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningentry',
            old_name='content',
            new_name='entry',
        ),
        migrations.RenameField(
            model_name='learningentry',
            old_name='text',
            new_name='topic',
        ),
    ]
